site_name: yuhutest
site_description: Yuhu Test
repo_url: https://github.com/LopsanAMO/Yuhu-Test
site_dir: site
copyright: Copyright &copy; 2020, <a href="https://github.com/LopsanAMO">LopsanAMO</a>.
dev_addr: 0.0.0.0:8001

nav:
  - Home: 'index.md'
  - API:
    - Authentication: 'api/authentication.md'
    - Users: 'api/users.md'
